### PR TITLE
Fix warnings after upgrade to Xcode 8.3 (Swift 3.1)

### LINKED ISSUE #47: Fix warnings after upgrade to Xcode 8.3 (Swift 3.1)
There are two new warnings issued:
1. `Double.Swift`, line 27
2. `ObserverSet.Swift`, line 127

### PR DESCRIPTION
**Pull request by ephraimkunz**
Resolves #47

### CODE REVIEW

File: Swiftification/ObserverSet.swift [hunk 1]
```diff
@@ -124,7 +124,7 @@ extension ObserverSet: CustomStringConvertible {
             entry in
             (entry.object === self
                 ? "\(entry.f)"
-                : "\(entry.object) \(entry.f)")
+                : "\(String(describing: entry.object)) \(entry.f)")
```
Comment (hiltonc) [inline Swiftification/ObserverSet.swift]: This will log "Optional(...)". Because `entry.object === self` at this point, we know that `entry.object` is not optional. Try this instead:

```swift
if let object = entry.object, object === self {
    return "\(object) \(entry.f)"
} else {
    return "\(entry.f)"
}
```

Comment (hiltonc) [inline Swiftification/ObserverSet.swift]: Ooops, that had a bug. Try this maybe?

```swift
if object === self {
    return "\(entry.f)"
} else if let object = entry.object {
    return "\(object) \(entry.f)"
} else {
    return "nil \(entry.f)"
}
```

Comment (hiltonc) [inline Swiftification/ObserverSet.swift]: Agh, you know what, this one doesn't really matter. Let's just go with what you originally had.

**Comment by hiltonc** [comment]
Can you increment the patch version in the podspec?
